compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java, compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfigAccess.java, compiler/src/org.graalvm.compiler.serviceprovider.jdk11/src/org/graalvm/compiler/serviceprovider/GraalServices.java, compiler/src/org.graalvm.compiler.serviceprovider.jdk13/src/org/graalvm/compiler/serviceprovider/GraalServices.java, compiler/src/org.graalvm.compiler.serviceprovider.jdk8/src/org/graalvm/compiler/serviceprovider/GraalServices.java, compiler/src/org.graalvm.compiler.serviceprovider/src/org/graalvm/compiler/serviceprovider/GraalServices.java
Cherry-picked the oracle/graal master commit for our 20.1 branch.
=> Expect AVX3Threshold on all JDKs >= 11.0.6 or JDK >= 14

.github/workflows/repo-sync.yml
Implements the approach discussed in #15
=> Sync on push only when workflow is edited, otherwise once a day 

.github/workflows/repo-sync.yml
=> Revert "Opens PR when a new OpenJDK EA release comes out"

README-Mandrel.md, README.md
=> Adds README-Mandrel.md

README-Mandrel.md
Applies text from https://github.com/graalvm/mandrel/pull/38#discussion_r441574414
=> fixup! Adds README\-Mandrel.md

.github/workflows/repo-sync.yml
=> Use redhat email in merges to make oca-bot happy

.github/workflows/quarkus.yml
Closes https://github.com/graalvm/mandrel/issues/20
=> Use mandrel-packaging in GH workflow

.github/workflows/quarkus.yml
Updates github workflow to match that of Quarkus, making all tests pass!
=> Update CI to match that of quarkus

.github/workflows/repo-sync.yml
=> Stops syncing oracle-master and oracle-20.1

substratevm/mx.substratevm/suite.py, substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGeneratorRunner.java, substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/agent/ClassInitializationTrackingVisitor.java, substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/agent/NativeImageBytecodeInstrumentationAgent.java, substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/agent/jdk8/lambda/LambdaMetaFactoryRewriteVisitor.java
=> Mandrel/20.1 backport oracle/graal/2543

substratevm/DEBUGINFO.md, substratevm/mx.substratevm/mx_substratevm.py, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/FileEntry.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debuginfo/DebugInfoProvider.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfAbbrevSectionImpl.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java, substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java, substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceManager.java
=> Mandrel/20.1 backport oracle/graal/2661

.github/workflows/quarkus.yml, compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/SingleImplementorInterfaceTest.java, compiler/src/org.graalvm.compiler.core.test/src/org/graalvm/compiler/core/test/inlining/InliningTest.java, compiler/src/org.graalvm.compiler.java/src/org/graalvm/compiler/java/BytecodeParser.java, compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/CallTargetNode.java, compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/java/MethodCallTargetNode.java, compiler/src/org.graalvm.compiler.phases.common/src/org/graalvm/compiler/phases/common/inlining/walker/InliningData.java, compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/classfile/ClassfileConstantPool.java, compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/classfile/ConstantPoolPatch.java, compiler/src/org.graalvm.compiler.serviceprovider.jdk11/src/org/graalvm/compiler/serviceprovider/GraalServices.java, compiler/src/org.graalvm.compiler.serviceprovider.jdk13/src/org/graalvm/compiler/serviceprovider/GraalServices.java, compiler/src/org.graalvm.compiler.serviceprovider.jdk8/src/org/graalvm/compiler/serviceprovider/GraalServices.java, compiler/src/org.graalvm.compiler.serviceprovider/src/org/graalvm/compiler/serviceprovider/GraalServices.java, compiler/src/org.graalvm.compiler.truffle.test/src/org/graalvm/compiler/truffle/test/PerformanceWarningTest.java, substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/infrastructure/ConstantPoolPatch.java, substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/infrastructure/WrappedConstantPool.java
=> Backports oracle/graal#2681

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java, substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/JDKSourceCache.java, substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceCache.java, substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceManager.java
Backport of https://github.com/oracle/graal/pull/2680
=> fix lookup of jvmci and compiler sources im JDK src.zip

substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfAbbrevSectionImpl.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfDebugInfo.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
Backport of https://github.com/oracle/graal/pull/2698
=> Omit stmt_list from CU info record when it has no associated line records

.github/workflows/quarkus.yml
=> Sync CI workflow with mandrel/20.1

README-Mandrel.md
=> README: mention that Mandrel doesn't support the image build server

substratevm/mx.substratevm/mx_substratevm.py, substratevm/mx.substratevm/testhello.py, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/FileEntry.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/StringTable.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
=> Fixes inlined code's cache paths for DWARF generation 

substratevm/mx.substratevm/testhello.py, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/DebugInfoBase.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/FileEntry.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java, substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java, substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageDebugInfoProvider.java, substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceCache.java, substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceCacheType.java, substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceManager.java
=> Remove jdk, graal, and src subdirectories from sources cache

substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/DefaultOptionHandler.java
Backport of https://github.com/oracle/graal/pull/2614
=> Prints JDK build number along with java.version

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ClassInitializationFeature.java
This reverts commit ea98895a56f64c07fa87102a71f657faf7ce3958 as discussed in #147
=> Revert "Do not raise an error if incomplete classpath is allowed #2556"

substratevm/mx.substratevm/mx_substratevm.py, substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaAWTSubstitutions.java, substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/SystemPropertiesSupport.java, substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java, substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JDKRegistrations.java, substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationAwt.java, substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/snippets/SubstrateGraphBuilderPlugins.java, substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/JNILibraryInitializer.java
Backports:
* https://github.com/oracle/graal/commit/5d2997a9ac8cafdfc6b5c316532165839ad7d1af
* https://github.com/oracle/graal/commit/75aa89e721e23356dbdb5f86ad58641e416ce8d5
Closes #171
=> Add awt support

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationAwt.java
Backports https://github.com/oracle/graal/pull/3032
=> Fix UnsatisfiedLinkError when using ImageIO and jpeg

.github/workflows/mandrel.yml
Let's keep this as draft at least until default branch can build (aka oracle#2933 gets resolved)
Also blocked by AdoptOpenJDK/openjdk-api-v3#319 and
=> [CI] Update workflow to get the matrix from json file

compiler/src/org.graalvm.compiler.serviceprovider.jdk8/src/org/graalvm/compiler/serviceprovider/GraalServices.java, substratevm/mx.substratevm/suite.py, substratevm/src/com.oracle.svm.graal.test/src/com/oracle/svm/graal/test/IsolatedSpeculationLogEncodingNativeTest.java, substratevm/src/com.oracle.svm.graal.test/src/com/oracle/svm/graal/test/IsolatedSpeculationLogEncodingTest.java, substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedCodeInstallBridge.java, substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedSpeculationLog.java, substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedSpeculationReasonEncoding.java, substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/SpeculationReasonEncodingClone.java
Backports https://github.com/oracle/graal/pull/2945 and https://github.com/oracle/graal/commit/64fc207db5f5a41f147f16e0c09496981a175a3e
=> Work around the absence of SpeculationReasonEncoding in OpenJDK11

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationAwt.java
Backports 9eb8b9efe9b8904165eb5b2e3d00e08ad9c7747c
Closes #198
=> Add new harfbuzz library to the native-image build

.github/workflows/mandrel.yml
This reverts commit d2c7141ba59014ce7ec8aa52765cd0e065a0f4f6.
=> Revert "CI: Temporarily disable builds with OpenJDK 11 EA"

.github/workflows/mandrel.yml
=> CI: Disable graal/master builds with OpenJDK 11 EA #214

.github/workflows/mandrel.yml
This reverts commit b73dec8b37102d8164a81e9a80aca3b916515eda.
=> Revert "CI: Disable graal/master builds with OpenJDK 11 EA #214"

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JDK11_0_10OrEarlier.java, substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JDK11_0_11OrLater.java, substratevm/src/com.oracle.svm.methodhandles/src/com/oracle/svm/methodhandles/Target_java_lang_invoke_MethodHandles_Lookup.java
Backport of https://github.com/oracle/graal/pull/3229
=> Fix builds with JDK 11.0.11 EA

.github/workflows/mandrel.yml
and test against both EA and GA versions of OpenJDK
=> CI: Update workflow to get the matrix from json file

README.md
Updated version of #222 to match https://github.com/graalvm/mandrel/blob/mandrel/21.1/README-Mandrel.md
=> Docs updated, Prerequisites section [default]

.github/workflows/base.yml, .github/workflows/nightly.yml, .github/workflows/repo-sync.yml
=> CI: Fixes in base.yml, repo-sync.yml and nightly.yml

.github/workflows/base.yml
Fixes rest-client failures: https://github.com/graalvm/mandrel/runs/2580759754?check_suite_focus=true
=> CI: Fix testing of builder images from quay.io

.github/workflows/nightly.yml
=> CI: Update ci to test 21.2 builder image as well

.github/workflows/base-windows.yml, .github/workflows/base.yml, .github/workflows/nightly.yml
Linux test: https://github.com/zakkak/mandrel/actions/runs/1387040812
Windows test: https://github.com/zakkak/mandrel/actions/runs/1387156777
Q2.2 with Mandrel 21.3 test: https://github.com/zakkak/mandrel/actions/runs/1387219384
Note: the builds succeed but the ITs fail due to https://github.com/quarkusio/quarkus/pull/20968
=> Test Q2.2 with Mandrel 21.3 and build GraalVM CE with libgraal

substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JNIRegistrationJavaNet.java
OpenJDK 11.0.14+1 got a backport of [JDK-8216417](https://bugs.openjdk.java.net/browse/JDK-8216417) which
got backported to Oracle JDK 11.0.13 one release earlier. Thus, we can re-use the patch.
Backports https://github.com/oracle/graal/commit/0d398e42d7248b1209396e28e88feb819a5a82be from https://github.com/oracle/graal/pull/3562
Closes #314
=> Support removal of java.net.Inet6Address.cached_scope_id in 11.0.14+1

.github/workflows/base-windows.yml, .github/workflows/base.yml
Test runs:
* Windows: https://github.com/zakkak/mandrel/actions/runs/1445056442
* Linux: https://github.com/zakkak/mandrel/actions/runs/1445055981
=> CI: Switch to adoptium releases

.github/workflows/base-windows.yml, .github/workflows/base.yml
See https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/
=> Set types for workflow inputs

.github/workflows/base-windows-wrapper.yml, .github/workflows/base-windows.yml, .github/workflows/base-wrapper.yml, .github/workflows/base.yml, .github/workflows/nightly.yml
Being tested in:
* https://github.com/zakkak/mandrel/actions/runs/1687762952
* https://github.com/zakkak/mandrel/actions/runs/1687818920
* https://github.com/zakkak/mandrel/actions/runs/1687959520
* https://github.com/zakkak/mandrel/actions/runs/1688304968
* https://github.com/zakkak/mandrel/actions/runs/1688307644
=> Extend github workflows to support testing Mandrel java17

.github/workflows/base-windows.yml, .github/workflows/base.yml
We should not report failures or passes to GH issues before merging a PR.
=> CI: Don't report results to GH issues for pull requests

.github/workflows/nightly.yml
The respective managed issues by the mandrel-bot are:
* https://github.com/graalvm/mandrel/issues/398
* https://github.com/graalvm/mandrel/issues/399
* https://github.com/graalvm/mandrel/issues/400
=> [CI] Report failures for Java11 wind tests plus Java17 linux & win
