graalvm/mandrel

substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfLineSectionImpl.java

Backport to 20.1 branch fix for https://github.com/oracle/graal/issues/2431.

[backport] correct computation of prologue size

---

.github/workflows/quarkus.yml
compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java

This is a backport of this fix in master:
https://github.com/graalvm/mandrel/commit/9514d29997d78d3585d9ed5c47196607ac1d1d93
It didn't apply cleanly due to context differences. I've applied the changes manually. Without this fix we are seeing assertions like this when running native-image on a HelloWorld:
```
Exception in thread "main" jdk.vm.ci.common.JVMCIError: VM config values not expected to be present in JDK 11 linux-amd64 (java.home=/disk/graal/upstream-sources/graal/sdk/mxbuild/linux-amd64/GRAALVM_E6EC3842EE_JAVA11/graalvm-e6ec3842ee-java11-20.1.0, java.vm.name=OpenJDK 64-Bit Server VM, java.vm.version=11.0.8-ea+7):
CodeInstaller::FRAME_COMPLETE at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:886) [value: 6]
at …
```

fix native-image on openjdk11.0.8

---

README-Mandrel.md

Tested on a fresh vanilla installation of Ubuntu 18.04 Desktop with:
```bash
wget https://github.com/graalvm/mandrel/releases/download/mandrel-20.1.0.0.Alpha1/mandrel-java11-linux-amd64-20.1.0.0.Alpha1.tar.gz
tar -xf mandrel-java11-linux-amd64-20.1.0.0.Alpha1.tar.gz
export JAVA_HOME="$( pwd )/mandrelJDK"
export GRAALVM_HOME="${JAVA_HOME}"
export PATH="${JAVA_HOME}/bin:${PATH}"
curl -O -J  https://code.quarkus.io/api/download
unzip code-with-quarkus.zip
cd code-with-quarkus/
./mvnw package -Pnative
./target/code-with-quarkus-1.0.0-SNAPSHOT-runner
```
[Quarkus guide](https://quarkus.io/guides/building-native-image#prerequisites) talks about apt too, so I would like to add this to the Mandrel doc as well.

Documentation: Ubuntu-like system dependencies

---

.github/workflows/quarkus.yml

The test is no longer available on quarkus master

Removes infinispan-embedded quarkus integration test

---

.github/workflows/quarkus.yml
.github/workflows/repo-sync.yml

First step towards Proposal 1 of https://oss.oracle.com/pipermail/graalvm-dev/2020-July/000071.html:
> Make the default branch contain only a README file explaining what Mandrel is, how it relates to Graal, and how to get your hands on it. This branch will also contain any workflows related to housekeeping, syncing branches, nightly testing, etc.
> This branch will not contain any code. So after `git clone https://github.com/graalvm/mandrel` and reading the README users will be asked to checkout another branch if they want to access the source code.

Sync and test graal/master instead of master

---

.github/workflows/quarkus.yml

mandrel/20.1 is currently being tested against the latest quarkus release (including CR releases at the moment) and master.
This approach has two cons:
1. Some tests are not passing in the releases (due to some maven configuration).
2. The latest release is not always the release we want to support for a given mandrel version. E.g., 20.1.0.x might need to support quarkus 1.7 and 1.8, but maybe not quarkus 1.9 (which will become the latest release at some point)
Instead of using the latest release, this PR starts using the release branch instead, e.g. branch 1.7 for Quarkus 1.7.
This way we will always test against the latest version of the releases we are interested in and the `master`

Test mandrel/20.1 against branch 1.7 instead of latest release

---

substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/LocalizationFeature.java

With JDK-8236548 in OpenJDK 11 an issue running
a generated native image may arise on programs using
TimeZone.getDisplayName(). With JDK-8236548 this might
become more noticeable since it now occurs on the
English locale too (no caching of English locales
happens any more).
Since all time zone data is included by default now,
also include the TimeZoneNames resource bundle by
default.
Closes: graalvm/mandrel#106
Backport of: https://github.com/oracle/graal/pull/2777

Fix missing localization info issue for timezones

---

.github/workflows/quarkus.yml

20.1 is supposed to support Quarkus 1.7.x, for later releases 20.2
should be used (https://github.com/quarkusio/quarkus/blob/f585d9d8c00f235059942aa9f81b7ccea06297af/core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java#L131)

CI: Stop testing Quarkus master with 20.1

---

.github/workflows/quarkus.yml

GraalVM organization no longer allows running third party actions other than those under:
```
docker/*,
graalvm/*,
oracle/*,
```
and actions created by GitHub.
Thus this PR removes the cancel-previous-runs action from our workflow and also adds skipDocs since it appears to be causing issues without testing any part of native-image.

[20.1] Remove cancel-previous-runs to conform to new rules and skipDocs

---

.github/workflows/quarkus.yml

GraalVM organization no longer allows running third party actions other than those under:
```
docker/*,
graalvm/*,
oracle/*,
```
and actions created by GitHub.
Thus this PR removes cancel-previous-runs action from the workflow.
It also backports #140 on 20.2

[20.2] Remove cancel-previous-runs ro conform to new rules + backport of #140

---

sdk/mx.sdk/mx_sdk_vm.py
substratevm/mx.substratevm/mx_substratevm.py
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/c/libc/GLibc.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/c/libc/LibCBase.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/c/libc/MuslLibc.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/NativeLibraries.java

20.1 backport of https://github.com/oracle/graal/commit/d7b5904db656d1313d6462a0034818dfccbbb69b
This is in preparation for #125 and corresponding fix in upstream OpenJDK packaging in https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/pull/10
We should only merge close to the OpenJDK 11.0.9 release. The main difference to https://github.com/oracle/graal/commit/d7b5904db656d1313d6462a0034818dfccbbb69b are in `substratevm/mx.substratevm/mx_substratevm.py`

Refactor static library search paths

---

compiler/src/org.graalvm.compiler.java/src/org/graalvm/compiler/java/FrameStateBuilder.java

Backport of: https://github.com/oracle/graal/commit/929dde28d8ba99b3d044be2b6fb86ce1625a2286

Clear lower half of two-slot value when upper half is not live

---

substratevm/mx.substratevm/suite.py
substratevm/src/com.oracle.svm.graal.test.jdk11/src/com/oracle/svm/graal/test/jdk11/IsolatedSpeculationLogEncodingNativeTest.java
substratevm/src/com.oracle.svm.graal.test.jdk11/src/com/oracle/svm/graal/test/jdk11/IsolatedSpeculationLogEncodingTest.java
substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedCodeInstallBridge.java
substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedSpeculationLog.java
substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedSpeculationReasonEncoding.java
substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/SpeculationReasonEncodingClone.java

Closes #146 
Upstream PR https://github.com/oracle/graal/pull/2945 not merged yet, but we can proceed to get 20.3 out and apply potential patches later.

Work around the absence of SpeculationReasonEncoding in OpenJDK11

---

substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGeneratorRunner.java

Backports:
* https://github.com/oracle/graal/commit/7f4e2f1b8013e1f697352de301add9fd2f9fb175
* https://github.com/oracle/graal/commit/6afdd1bed96bae714f136e3deee0278a0d216335
Fixes `ResourcesITCase` from Quarkus `Main` test suite.
Relates to: #169 and https://github.com/quarkusio/quarkus/issues/13472

Rework passing of arguments between the driver and the native-image generator runner

---

substratevm/mx.substratevm/testhello.py
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java

Cherry pick of https://github.com/graalvm/mandrel/pull/178
Fixes failure of debugSymbolsSmokeGDB (see https://ci.modcluster.io/view/Mandrel/job/mandrel-linux-integration-tests/35/LABEL=el8,MANDREL_VERSION=21.0/console)
This is not needed in Mandrel >21.0 due to https://github.com/oracle/graal/pull/3046
(It might be worth pushing upstream for inclusion in GraalVM CE 20.3.x though)

Dynamically choose class delimiter for debug entries

---

.github/workflows/mandrel.yml

* Backport of https://github.com/graalvm/mandrel/pull/231
* Use mandrel-packaging 20.3
* Test branch 1.11 (instead of latest release) and main

CI: 20.3 updates

---

.github/workflows/mandrel.yml

Fixes failures due to not fount docker image (see https://github.com/graalvm/mandrel/runs/2224868590?check_suite_focus=true#step:7:34)

CI: use script from quarkus to reclaim space

---

README-Mandrel.md

Updated version of #202 to match https://github.com/graalvm/mandrel/blob/mandrel/21.1/README-Mandrel.md

Docs updated, Prerequisites section [20.3]

---

.github/workflows/base-windows.yml
.github/workflows/base.yml

mx is close to removing python2 support and the CI is currently failing
due to https://github.com/graalvm/mx/issues/238

CI: Force the use of python3

---

.github/workflows/base-windows.yml
.github/workflows/base.yml

When grepping the results of ls-remote to get the commit hash
corresponding to the given tag/branch we need to treat quarkus-version
as a fixed string to avoid treating dots as "any char"

CI: Treat quarkus-version as a fixed string

---

.github/workflows/base.yml

Using a relevant path results in the following exception when testing
1.11.7.Final as seen in #269 :
```
Caused by: java.lang.NullPointerException
at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.resolveSettingsFile(BootstrapMavenContext.java:321)
at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getUserSettings(BootstrapMavenContext.java:180)
at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getEffectiveSettings(BootstrapMavenContext.java:241)
at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.isOffline(BootstrapMavenContext.java:218)
at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.newRepositorySystem(BootstrapMavenContext.java:648)
at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getRepositorySystem(BootstrapMavenContex …
```

CI: pass absolute path to mvn --settings

---

substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrEventSubstitution.java
substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrFeature.java

Backports: https://github.com/oracle/graal/commit/bdaf8c260e7e880145df8ac8c09b19570c6c37c6
Fix reflection registration for JFR eventHandler fields
Closes #270

Backport reflection registration fix for JFR eventHandler fields

---

substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrManager.java

Backports https://github.com/oracle/graal/pull/3639
"Enables parsing units for maxsize, fixes units for delay in JfrManager.java"

Backport "Enables parsing units for maxsize, fixes units for delay in JfrManager.java"

---

.github/workflows/nightly.yml

nighlty requires an AUTH token to trigger the builds and users openning
PRs normally don't have that token set up, resulting in the pipeline
failing.

CI: Disable nightly pipeline on PRs

---

.github/workflows/nightly.yml

See https://github.com/quarkusio/quarkus/pull/20894

CI: Quarkus main is now using GraalVM/Mandrel 21.3

---

.github/workflows/base-windows.yml
.github/workflows/base.yml

Adds mandrel-integration-tests to the CI matrix.
@Karm please advise which tests we should enable. The current configuration takes 7 minutes for the hosted version, and 4 minutes for the builder-image so there is room to add more tests (ideally I would like all of them to run).

CI: Add job to run mandrel-integration-tests

---

.github/workflows/base-windows.yml
.github/workflows/base.yml

Avoid issues like:
```
Artifact name is not valid: test-reports-mandrel-it-mandrel-graal/master-Qf4ecfa97b775e497e225191141dd2ff758ea72ab-. Contains character: "/". Invalid artifact name characters include: ",:,<,>,|,*,?,\,/.
```

CI: Use simple name for test reports artifact on failure

---

.github/workflows/base-windows.yml
.github/workflows/base.yml
.github/workflows/main.yml

Our current setup requires manually triggering CI for testing pull requests and that doesn't always work well.
This PR enables the following matrix for 21.3:
JDKs: latest ea and latest ga OpenJDK 11
Quarkus: 2.2 branch, latest release (currently 2.4.1.Final), and main branch
The reasons I chose these parameters are the following:
* GA builds should be tested for all patches before a patch release
* EA builds help us avoid introducing regressions for the next CPU release
* Q 2.2 is expected to move to 21.3 at some point
* 21.3 is currently the default for Quarkus main so we want to make sure it works fine with it
* 21.3 will become the default in the next Quarkus release (2.5?) so we want to make sure it works fine with it (currently the latest Quarkus release is 2.4.1.Final which still …

CI: Add windows and linux workflows for 21.3 branch

---

.github/workflows/base-windows.yml
.github/workflows/base.yml
.github/workflows/main.yml

Our current setup requires manually triggering CI for testing pull requests and that doesn't always work well.
This PR enables the following matrix for 21.2:
JDKs: latest ea and latest ga OpenJDK 11
Quarkus: 2.2 branch
21.2 is no longer supported in Quarkus `main` so testing only with Quarkus 2.2 is enough.

CI: Add windows and linux workflows for 21.2 branch

---

.github/update_quarkus_version.sh
.github/workflows/base-windows.yml
.github/workflows/base.yml

Makes mandrel-integration-test not apply quarkus_main.patch which breaks the tests on 2.2.
See https://github.com/Karm/mandrel-integration-tests/pull/64
Test runs:
* [2.2 - windows](https://github.com/zakkak/mandrel/actions/runs/1508481081)
* [2.2 - linux](https://github.com/zakkak/mandrel/actions/runs/1508486872)
* [2.5 - windows](https://github.com/zakkak/mandrel/actions/runs/1507619281)
* [2.5 - linux](https://github.com/zakkak/mandrel/actions/runs/1507078277)

CI: Change quarkus.version for Quarkus 2.2

---

.github/workflows/base-windows-wrapper.yml
.github/workflows/base-windows.yml
.github/workflows/base-wrapper.yml
.github/workflows/base.yml
.github/workflows/nightly.yml

* Allows the whole matrix to run under a single CI run while making the base workflow reusable by other branches so that we can stop replicating CI pipelines in release branches. This has the following benefits:
1. The whole matrix runs a lot faster (~4h for all combinations instead of ~2h per combination in some cases)
**Before**:
**After**: 
2. It's much easier to understand what fails in the whole matrix by inspecting a single page (it used to be 8)
3. We can now test the workflow in PRs that affect it
* Adds wrappers for workflow_dispatch, so that we can still run custom jobs with `gh workflow run`...
* Makes artifacts unique per reusable workflow inputs. This is necessary since when using reusable workflows and calling a reusable workflow multiple times from the same caller workflow …

Reusable workflows

---

.github/workflows/base-windows.yml
.github/workflows/base.yml

This allows job "mandrel-integration-tests" to run with the "latest" Quarkus release by using its tag as defined by job "get-test-matrix".

CI: Don't use commit hash for release tags to handle latest in mandrel IT

---

.github/workflows/base-windows.yml
.github/workflows/base.yml

As of
https://github.com/Karm/mandrel-integration-tests/commit/672ddd28e13b3395938ac4963f5e911e18570b5d
mandrel-integration-tests expects the quarkus version to match
X.Y.Z.suffix

CI: Use 2.2.999 as the Quarkus version for 2.2 branch

---

.github/workflows/main.yml
substratevm/mx.substratevm/testhello.py
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/ClassEntry.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/MethodEntry.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/debugentry/Range.java
substratevm/src/com.oracle.objectfile/src/com/oracle/objectfile/elf/dwarf/DwarfInfoSectionImpl.java
substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/JNIJavaCallTrampolines.java
substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/JNIJavaCallWrappers.java
substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/access/JNIAccessFeature.java
substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/hosted/JNICallWrapperFeature.java
substratevm/src/com.oracle.svm.jni/src/com/oracle/svm/jni/hosted/JNINativeCallWrapperSubstitutionProcessor.java

Backports https://github.com/oracle/graal/pull/4121 since without it debug info generation won't work in some cases when assertion are enabled (see https://github.com/oracle/graal/issues/4018).
Closes #345

Backport of oracle/graal #4121 fixing debug info generation

---

.github/quarkus-ecosystem-issue.java
.github/workflows/base-windows.yml
.github/workflows/base.yml
.github/workflows/nightly.yml

This PR enables our CI runs to report results on github issues like [this one](https://github.com/quarkusio/quarkus/issues/8593) using a [bot account](https://github.com/mandrel-bot). The results can be reported in a per configuration manner, so that we don't have to spam people with false negatives from experimental configurations etc. People responsible for monitoring the stability of a configuration will be able to subscribe to the corresponding issue and get notified of changes.

Add support for reporting results a la quarkus-ecosystem-ci style

---

.github/workflows/base-windows.yml
.github/workflows/base.yml

The native-tests job is run using a matrix which results in multiple
instances of the job being run per workflow run. This resulted in
multiple reports being generated as well. So for instance if the
native-tests job would run 6 times, with only half of them passing the
workflow could end up opening and closing the corresponding GH issue 6
times, while we would like it to only open it once if closed or post a
message that the workflow is still failing if already open. By moving
the report logic to a separate job that depends on the native-tests job
and reports the aggregated result of all the instances of the latter we
achieve our goal.

CI: Fix CI issue reporting

---

.github/workflows/base-windows.yml

`windows-latest` has been updated to `windows-2022` which is causing our CI to fail. This PR pins our runners to `windows-2019`. Note that we can build and test Mandrel on `windows-2022` as well (after adjusting the Visual Studio paths), but IMO it's better to stick with 2019 for now.

CI: Pin windows GH runners to windows-2019

---

substratevm/src/com.oracle.svm.core.jdk16/src/com/oracle/svm/core/jdk16/RecordSupportJDK16OrLater.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/hub/DynamicHub.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/hub/DynamicHubCompanion.java
substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/RecordSupport.java
substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/hosted/ReflectionDataBuilder.java

Fix for https://github.com/oracle/graal/issues/3984 till it gets merged upstream.

Implement annotation support for RecordComponents

---

.github/workflows/base-windows.yml
.github/workflows/base.yml

The script depends on https://github.com/hub4j/github-api which fails with:
```
java.io.UncheckedIOException: java.io.IOException: Failed to set the custom verb
at Report.run(quarkus-ecosystem-issue.java:99)
at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
at picocli.CommandLine.access$900(CommandLine.java:145)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
at picocli.CommandLine.execute(CommandLine.java:1904)
at Report.main(quarkus-ecosystem-issue.java:108)
Caused by: java.io.IOException: Failed to set the custom verb …
```

CI: Fix issues related to quarkus-ecosystem-issue script

---

.github/workflows/base-windows.yml
.github/workflows/base.yml

`mx` now requires a python version >= 3.8

CI: Fix python version to 3.8

---

.github/workflows/base-windows.yml
.github/workflows/base.yml

https://github.com/quarkusio/quarkus/pull/25986 allows Quarkus native to
work with the image-builder running on module path.
Reverts: #388, #390, #391
Closes: #389

CI: Re-enable running image-builder on module path

---

.github/workflows/base.yml

Fixes build failures for Gradle Plugin
```
FAILURE: Build failed with an exception.
> Task :gradle-application-plugin:compileJava FAILED
* What went wrong:
Execution failed for task ':gradle-application-plugin:compileJava'.
> Could not resolve all files for configuration ':gradle-application-plugin:compileClasspath'.
> Could not find plexus-utils-3.4.1.jar (org.codehaus.plexus:plexus-utils:3.4.1).
Searched in the following locations:
file:/home/runner/.m2/repository/org/codehaus/plexus/plexus-utils/3.4.1/plexus-utils-3.4.1.jar
```

CI: Use maven wrapper to build Quarkus

---

.github/quarkus-ecosystem-issue.java
.github/workflows/base-windows.yml
.github/workflows/base.yml

Failures to build Mandrel/Graal or Quarkus should not result in openning GH issues to mandrel-integration-tests

Only report failures to mandrel-integration-tests when Mandrel IT runs
